### ISSUE TITLE
Expansion green/red button position is not working properly on old Firefox versions

### ISSUE THREAD

**Issue by ghost** [DataTables/Responsive#5]
This patch is intended for old Firefox versions only (e.g. Firefox 24). In recent versions works properly:

``` css
table.dataTable.dtr-inline.collapsed tbody td:first-child:before,
table.dataTable.dtr-inline.collapsed tbody th:first-child:before {
    display: inline-block;
    position: relative;
    top: auto;
    left: auto;
    margin-left: -24px;
    margin-right: 8px;
}
```

Absolute positioning misbehaves when doing nested scrolling after expanding (keeps buttons fixed in the parent), replaced with relative, using inline-block to prevent block line change and adding required right margin.
